[project]
name = "fuzzy-camera"
version = "0.1.0"
description = ""
authors = [
    {name = "megahomyak",email = "g.megahomyak@gmail.com"}
]
requires-python = ">=3.13"
dependencies = [
    "opencv-python (>=4.13.0.92,<5.0.0.0)",
    "pysimplegui (>=6.0,<7.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
